### ISSUE TITLE
Trouble with mpu9250 on intel Edison

### ISSUE THREAD

**Issue by AD-Aleksandrov** [PX4/DriverFramework#101]
MPU9250.
Guys, help please!
I take data several times but after that the driver is hung. 
And the driver is working random time before to hang.

**Comment by julianoes** [comment]
Oh, this runs on Edison? :smile: What git hash are you using? Are you running the unit test? Can you put a `DF_LOG_INFO` in _measure() and check what happens?

**Comment by AD-Aleksandrov** [comment]
I run the latest version. Yes, unit test. And after your commit, nothing changed: the driver is hung after a while. 
I tried to understand where is bug, there is an opinion the driver is hung in SPIDevObj::_bulkRead, but i am not sure. 
Thank you.

**Comment by julianoes** [comment]
Well, you'll have to be sure exaclty where it hangs, otherwise it's hard to understand and fix :).

**Comment by AD-Aleksandrov** [comment]
Hang in SPIDevObj::_bulkRead, calling ::ioctl(), line 322

**Comment by julianoes** [comment]
So, if the [ioctl](https://github.com/PX4/DriverFramework/blob/master/framework/src/SPIDevObj.cpp#L322) hangs, can you debug further inside that call, so in the SPI library on the edison?

**Comment by AD-Aleksandrov** [comment]
What do you think about failed test: offsetTime(), does depend on it something?

**Comment by julianoes** [comment]
`offsetTime()` is used for the scheduling of the DriverFramework but not inside `ioctl()` calls which happen in the respective drivers such as the SPI/I2C libs on the platform.

**Comment by julianoes** [comment]
@AD-Aleksandrov We would need additional information and help for this. I'll close it for now, feel free to re-open if you have a fix or more info.

**Comment by julianoes** [comment]
Presumably addressed in #123.
