### ISSUE TITLE
/dev/ access

### ISSUE THREAD

**Issue by egorf** [PX4/DriverFramework#109]
Hi!

This is more of a question, than an issue. It's not exactly clear from the example, whether `/dev/gyro` will be available after starting the framework. Can the gyro be used by another application by reading/writing to `/dev/gyro`, kernel module style?

**Comment by julianoes** [comment]
@mcharleb: I'm sure you can answer this best, thanks.

**Comment by egorf** [comment]
Guys? Any update on this?

**Comment by bkueng** [comment]
If you mean different user-space linux applications, then no, it cannot be used.

**Comment by egorf** [comment]
Thanks
