### ISSUE TITLE
Fix 2nd pressure sensor driver

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/DriverFramework#118]
@eyeam3 This here is incorrect:
https://github.com/PX4/DriverFramework/blob/master/drivers/ms5607/MS5607.cpp#L354

It will block the execution of other sensor drivers because they run together in a work queue on the same thread.

It will need the same fix as this one here:
https://github.com/PX4/DriverFramework/commit/29b18fba71992267f9056de32ae8090e4cc4a8a8

@julianoes FYI

**Comment by eyeam3** [comment]
Has been fixed with #142.
