### ISSUE TITLE
could you add rc in. rc out. adc sim.  i want use  pxio board

### ISSUE THREAD

**Issue by cudnn** [PX4/DriverFramework#129]

**Comment by julianoes** [comment]
This has recently been added in https://github.com/PX4/Firmware/pull/4938. Docs will follow.

**Comment by cudnn** [comment]
navio 2 board use diffrent spi between stm32 and imu。i want to use the same spi 。

**Comment by julianoes** [comment]
I don't understand what you mean. If you want people to do something for you, you might have to put a little bit more effort into describing your problem.
