### ISSUE TITLE
DPLF settings for all drivers need review

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/DriverFramework#164]
@mcharleb @julianoes on average the DPLF setting should be set around 30-50 Hz on all platforms. We need to make sure that's the case.

**Comment by LorenzMeier** [comment]
@Stifael @ChristophTobler Please consult with @tumbili and @eyeam3 for details.

**Comment by julianoes** [comment]
Most drivers have been moved to the PX4 Firmware repo, see https://github.com/PX4/Firmware/pull/13900.

I'm therefore closing the issues here.
