### ISSUE TITLE
IMU delta time calculation problem

### ISSUE THREAD

**Issue by RomanBapst** [PX4/DriverFramework#166]
The IMU drives are applying a first order low pass to the number of packets available in the FIFO buffer, see https://github.com/PX4/DriverFramework/blob/master/drivers/mpu6050/MPU6050.cpp#L445
The filtered value is used to calculate the delta time for each sensor sample.

This does not make sense and requires clarification of the original intent.

**Comment by julianoes** [comment]
Most drivers have been moved to the PX4 Firmware repo, see https://github.com/PX4/Firmware/pull/13900.

I'm therefore closing the issues here.
