### ISSUE TITLE
coverity defects

### ISSUE THREAD

**Issue by dagar** [PX4/DriverFramework#170]
DriverFramework defects from Coverity.

You can access them https://scan.coverity.com/projects/px4-firmware/view_defects
Ping me if you need access.

![screenshot from 2017-01-04 12-30-37](https://cloud.githubusercontent.com/assets/84712/21652208/c9ee3542-d279-11e6-8255-2749a112cb79.png)

**Comment by julianoes** [comment]
@dagar wow that's interesting!

**Comment by mcharleb** [comment]
@dagar I get "You are not authorized to access this page"

**Comment by dagar** [comment]
It looks like you have to be a member of the PX4 project on Coverity to access defect details. You should both receive invites shortly.
