### ISSUE TITLE
I2C Driver: Confusion about operation on code inspection

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/DriverFramework#18]
@mcharleb I don't see from looking at the code how the BMP280 would return valid data - have you tested the version in master on hardware?

The reason I ask is the following sequence:

Registers are being read here:
https://github.com/PX4/DriverFramework/blob/master/drivers/pressure/bmp280/BMP280.cpp#L172

The I2C dev handle only becomes active here:
https://github.com/PX4/DriverFramework/blob/master/drivers/i2c/I2CDevObj.cpp#L47
which is called *after the register reads*
here:
https://github.com/PX4/DriverFramework/blob/master/drivers/pressure/bmp280/BMP280.cpp#L183

How are the read regs working if the FD does not exist yet?

**Comment by julianoes** [comment]
This has been resolved, the BMP280 unit test works.
