### ISSUE TITLE
Bebop 2 Rangefinder real-time issue

### ISSUE THREAD

**Issue by bartslinger** [PX4/DriverFramework#232]
The range finder uses the SPI bus to generate pulses. This is a blocking SPI write call at a relatively low frequency. 32 bytes = 190 bits, at 320kHz equates to 800us. That's already quiet a long time, but it turns out that the SPI write call can take much longer. I put a perf counter around the following write call: https://github.com/PX4/DriverFramework/blob/master/drivers/bebop_rangefinder/BebopRangeFinder.cpp#L130 and got the following:

`1327 events, 1530673us elapsed, 1153.48us avg, min 887us max 8625us 779.674us rms`

**max 8625us** is way too much delay in a thread that is also responsible for the IMU.
I'm just posting this to share my findings. I don't use the rangefinder myself and I don't have plans to fix this.

**Comment by julianoes** [comment]
Most drivers have been moved to the PX4 Firmware repo, see https://github.com/PX4/Firmware/pull/13900.

I'm therefore closing the issues here.
