### ISSUE TITLE
Raspberry Only HCM5983 Compass Calibration not working

### ISSUE THREAD

**Issue by meanpenguin** [PX4/DriverFramework#234]
Using a Raspberry Pi with a NEO-M8T GPS and an external hmc5983 compass.
Utilizing the Navio2 Raspberry Pi image

Had some initial issues so the first problem was tracked down to the i2c bus.
Given that the raspberry only has /dev/i2c-1. 
Changed code from using /dev/i2c-2 to /dev/i2c-1 in 
/src/Firmware/src/lib/DriverFramework/drivers/hmc5883/hmc5883.hpp
#define MAG_DEVICE_PATH "/dev/i2c-1"

**Issue**
Any help in where I should look for the possible resolution to the error below?
Would the compass being a hcm5983 not be supported by the hcm5883 driver?  they seem to be compatible compasses and return the same id 1E in i2cdetect.
(Note: I utilized a python code to read in values from the hcm5983 and received values so know that the compass is connected properly and functioning)

px4 starts up OK
But receives: WARN  [commander] Preflight Fail: Compass #0 uncalibrated

**When I start compass calibration,I am getting the error below.**
682416 error: setting sensor mode failed
688951 Error: i2c write failed. Reported -1 bytes written
689072 Error: i2c write failed. Reported -1 bytes written
continuously repeated ....

** Added debug just before publish and the values are changing as I move the compass. **
 DF_LOG_ERR("Data published x=%lf, y=%lf, z=%lf", (double)m_sensor_data.field_x_ga, (double)m_sensor_data.field_y_ga, (double)m_sensor_data.field_z_ga);
_publish(m_sensor_data);

But, in calibration mode, getting lots of i2c write failed 
and the calibration does not complete.

** Listener is outputting compass values **
pxh> listener sensor_mag 5
TOPIC: sensor_mag instance 0 #1
 sensor_mag_s
        timestamp: 1579146145  (0.001190 seconds ago)
        error_count: 0
        device_id: 4398600 (Type: 0x43, UNKNOWN:1 (0x1E))
        x: 0.1312
        y: -0.1982
        z: 0.5018
        temperature: 0.0000
        scaling: 0.0000
        x_raw: 0
        y_raw: 0
        z_raw: 0
        is_external: True

**Comment by julianoes** [comment]
All drivers have been moved to the PX4 Firmware repo, see https://github.com/PX4/Firmware/pull/13900.

I'm therefore closing the issues here.
