### ISSUE TITLE
DSP console flodded with printfs

### ISSUE THREAD

**Issue by julianoes** [PX4/DriverFramework#236]
The DSP console is unusable because it gets flodded with lines like this:

```
    428615: HAP:59:443459520 MPU9250::_measureData: FIFO Count: 0 (MPU9250.cpp:574)
```

**Comment by smnogar** [comment]
Note that this corresponds with IMU error events and the IMU reaches the 10k event threshold around 5 minutes in my case. This is on a snapdragon flight.

**Comment by julianoes** [comment]
All drivers have been moved to the PX4 Firmware repo, see https://github.com/PX4/Firmware/pull/13900.

I'm therefore closing the isssues here.
