### ISSUE TITLE
Compile error: sys/ttydefaults.h

### ISSUE THREAD

**Issue by julianoes** [PX4/DriverFramework#25]
```dspal/include/termios.h:99:10: fatal error: 'sys/ttycom.h' file not found```
and
```dspal/include/termios.h:100:10: fatal error: 'sys/ttydefaults.h' file not found```

This happens when trying to compile the PX4 GPS driver.
Where would this file be? What is it for?

**Comment by LorenzMeier** [comment]
Its a BSD standard header. Either missing or the QuRT default include path is missing.

**Comment by julianoes** [comment]
A current workaround is pushed here: https://github.com/PX4/dspal/commit/eba0a18728aace328219d8985a08c7a506886b11

**Comment by jywilson** [comment]
DSPAL does not currently support the termios API's.  The same functionality is provided in the form of IOCTL's.

**Comment by julianoes** [comment]
@jywilson Understood, so the workaround (see https://github.com/PX4/dspal/commit/eba0a18728aace328219d8985a08c7a506886b11) is wrong?

**Comment by julianoes** [comment]
Closing for now, until there is termios support, see #30.
