### ISSUE TITLE
poll and pollfd not available?

### ISSUE THREAD

**Issue by julianoes** [PX4/DriverFramework#26]
Is it possible that we currently can't access poll and pollfd on QURT? This is needed in the GPS driver which wants to poll on the file descriptor of the UART.

See http://pubs.opengroup.org/onlinepubs/009695399/basedefs/poll.h.html

**Comment by LorenzMeier** [comment]
Currently looks like this might require non-standard / non-POSIX compliant use of callbacks.

**Comment by LorenzMeier** [comment]
https://github.com/ATLFlight/dspal/blob/master/test/dspal_tester/adsp_proc/serial_test_imp.c

**Comment by julianoes** [comment]
https://github.com/ATLFlight/dspal/blob/master/test/dspal_tester/adsp_proc/serial_test_imp.c#L212

**Comment by mcharleb** [comment]
@jywilson Is poll() supported in DSPAL?

**Comment by jywilson** [comment]
No, poll is not supported in DSPAL.  It's something we can do but it would not be a trivial change.

Can you give me some idea of how important such a change is, just in terms of trying to decide what to work on first?

**Comment by julianoes** [comment]
All the issues here labelled with "enhancement" are nice-to-haves but not blocking.

Of importance are internal mag and `/dev/mem` locking.

**Comment by LorenzMeier** [comment]
@jywilson Is it feasible to remove poll() from your header for the time being then? It's super confusing that it does compile but doesn't work. What is the timeline to add it?

**Comment by jywilson** [comment]
What headers are you referring to?  I couldn't find a reference to a poll function in the DSPAL headers, the Hexagon SDK headers, or the Hexagon Tools headers.

**Comment by julianoes** [comment]
Stale, closing.
