### ISSUE TITLE
Work queue change breaks SITL

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/DriverFramework#39]
@mcharleb I had to make the changes in 67cbaea to resurrect SITL. I made them in a way so they do not affect QuRT. Can you help us to understand if you think your recent change in https://github.com/PX4/DriverFramework/commit/e62faaccae8775fd4dc237d4c43fb29a62603014 was bad or if the barosim driver has a bug which was exposed by the change?

**Comment by julianoes** [comment]
Fixed in #43.
