### ISSUE TITLE
Instructions how to use tests

### ISSUE THREAD

**Issue by julianoes** [PX4/DriverFramework#41]
There seem to be unit tests for the DriverFramework, however, I don't see instructions how to use them.

**Comment by mcharleb** [comment]
@julianoes I am back in SD. I can help you run the unit tests.

**Comment by julianoes** [comment]
@mcharleb How do I run the tests?

**Comment by julianoes** [comment]
Done, see https://github.com/PX4/DriverFramework/commit/d1e0b6e2beff3b2244c67a550fb32dd37f9858e8
