### ISSUE TITLE
Add mag support to MPU9250 driver

### ISSUE THREAD

**Issue by julianoes** [PX4/DriverFramework#60]
It would be great to have support for the mag included in the MPU9250.

The driver is here: https://github.com/PX4/DriverFramework/tree/master/drivers/mpu9250
And the wrapper for PX4 is here: https://github.com/PX4/Firmware/tree/master/src/platforms/posix/drivers/df_mpu9250_wrapper

I suggest to start this work after #57 is merged.

**Comment by jywilson** [comment]
You can assign this issue to me.  It's something I am working on now and should have done this week.

**Comment by julianoes** [comment]
Fixed with #86 / #88, thanks @jywilson.
