### ISSUE TITLE
The DF timer includes drift

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/DriverFramework#68]
@mcharleb @jywilson If you ask the DF for a callback at a 4000 us interval you're getting 4000 us + scheduling overhead, not 4000 us on average, which is a problem for us. I will look with @bkueng into this, but if you have availability it would be great if you could propose a fix.

**Comment by jywilson** [comment]
The work queues might need to be optimized.  Also, we can experiment with thread priorities to see if we can make it more deterministic.  

Is there a particular target latency you would like to see?  What level of jitter from the target 4000 us would be considered acceptable?  

If you could produce some standalone sample code that demonstrates the problem, this would really help in validating that a potential fix is making a difference.

**Comment by mcharleb** [comment]
I can change it to expire at last expiry time + delta vs current time + delta

**Comment by LorenzMeier** [comment]
We see 4200 - 6000 us instead of 4000. NuttX gives us 4 us jitter. I would love to see something closer to that order of magnitude.

**Comment by mcharleb** [comment]
It looks like this was fixed in #71
